### ISSUE TITLE
Issue-bro

### ISSUE THREAD

**Issue by JamesRyo** [JamesRyo/Commune#10]
Automated Review Comments
Issues in Dockerfile:
  - (13, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
Issues in commune/bittensor/bittensor_module.py:
  - (1, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
  - (17, 'Line exceeds 80 characters')
  - (17, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
Issues in commune/bittensor/nucleus/nucleus_impl.py:
  - (7, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (62, 'Line exceeds 80 characters')
  - (74, 'Line exceeds 80 characters')
  - (75, 'Line exceeds 80 characters')
  - (78, 'Line exceeds 80 characters')
  - (85, 'Line exceeds 80 characters')
  - (86, 'Line exceeds 80 characters')
  - (87, 'Line exceeds 80 characters')
  - (88, 'Line exceeds 80 characters')
  - (90, 'Line exceeds 80 characters')
  - (91, 'Line exceeds 80 characters')
  - (92, 'Line exceeds 80 characters')
  - (93, 'Line exceeds 80 characters')
  - (104, 'Line exceeds 80 characters')
  - (106, 'Line exceeds 80 characters')
  - (107, 'Line exceeds 80 characters')
  - (113, 'Hardcoded string found')
  - (122, 'Line exceeds 80 characters')
  - (123, 'Line exceeds 80 characters')
  - (131, 'Line exceeds 80 characters')
  - (132, 'Line exceeds 80 characters')
  - (133, 'Line exceeds 80 characters')
  - (135, 'Line exceeds 80 characters')
  - (140, 'Line exceeds 80 characters')
  - (151, 'Line exceeds 80 characters')
  - (156, 'Line exceeds 80 characters')
  - (160, 'Line exceeds 80 characters')
  - (164, 'Line exceeds 80 characters')
  - (169, 'Hardcoded string found')
  - (190, 'Line exceeds 80 characters')
  - (191, 'Line exceeds 80 characters')
  - (192, 'Line exceeds 80 characters')
  - (193, 'Line exceeds 80 characters')
  - (198, 'Line exceeds 80 characters')
  - (199, 'Line exceeds 80 characters')
  - (200, 'Line exceeds 80 characters')
  - (201, 'Line exceeds 80 characters')
  - (202, 'Line exceeds 80 characters')
  - (203, 'Line exceeds 80 characters')
  - (210, 'Line exceeds 80 characters')
  - (210, 'Missing docstring for function')
  - (211, 'Line exceeds 80 characters')
  - (213, 'Line exceeds 80 characters')
  - (219, 'Line exceeds 80 characters')
  - (220, 'Line exceeds 80 characters')
  - (227, 'Line exceeds 80 characters')
  - (231, 'Line exceeds 80 characters')
  - (235, 'Line exceeds 80 characters')
  - (241, 'Line exceeds 80 characters')
  - (244, 'Line exceeds 80 characters')
  - (250, 'Line exceeds 80 characters')
  - (259, 'Line exceeds 80 characters')
  - (259, 'Hardcoded string found')
  - (265, 'Line exceeds 80 characters')
  - (266, 'Line exceeds 80 characters')
  - (267, 'Line exceeds 80 characters')
  - (272, 'Line exceeds 80 characters')
  - (276, 'Line exceeds 80 characters')
  - (277, 'Line exceeds 80 characters')
  - (281, 'Line exceeds 80 characters')
  - (285, 'Line exceeds 80 characters')
  - (290, 'Line exceeds 80 characters')
  - (294, 'Line exceeds 80 characters')
  - (296, 'Line exceeds 80 characters')
  - (298, 'Line exceeds 80 characters')
  - (301, 'Line exceeds 80 characters')
  - (302, 'Line exceeds 80 characters')
  - (304, 'Line exceeds 80 characters')
  - (305, 'Line exceeds 80 characters')
  - (310, 'Line exceeds 80 characters')
  - (322, 'Line exceeds 80 characters')
  - (322, 'Missing docstring for function')
  - (324, 'Line exceeds 80 characters')
  - (332, 'Line exceeds 80 characters')
  - (336, 'Line exceeds 80 characters')
  - (337, 'Line exceeds 80 characters')
  - (341, 'Line exceeds 80 characters')
  - (343, 'Line exceeds 80 characters')
  - (345, 'Hardcoded string found')
  - (350, 'Line exceeds 80 characters')
  - (352, 'Line exceeds 80 characters')
  - (353, 'Line exceeds 80 characters')
  - (354, 'Line exceeds 80 characters')
  - (355, 'Line exceeds 80 characters')
  - (362, 'Line exceeds 80 characters')
  - (364, 'Line exceeds 80 characters')
  - (372, 'Line exceeds 80 characters')
  - (382, 'Line exceeds 80 characters')
  - (385, 'Line exceeds 80 characters')
  - (386, 'Line exceeds 80 characters')
  - (387, 'Line exceeds 80 characters')
  - (388, 'Line exceeds 80 characters')
  - (388, 'Hardcoded string found')
  - (389, 'Line exceeds 80 characters')
  - (389, 'Hardcoded string found')
  - (390, 'Line exceeds 80 characters')
  - (390, 'Hardcoded string found')
  - (391, 'Line exceeds 80 characters')
  - (391, 'Hardcoded string found')
  - (392, 'Line exceeds 80 characters')
  - (392, 'Hardcoded string found')
  - (393, 'Line exceeds 80 characters')
  - (393, 'Hardcoded string found')
  - (394, 'Line exceeds 80 characters')
  - (395, 'Line exceeds 80 characters')
  - (396, 'Line exceeds 80 characters')
  - (397, 'Line exceeds 80 characters')
  - (398, 'Line exceeds 80 characters')
  - (399, 'Line exceeds 80 characters')
  - (402, 'Line exceeds 80 characters')
  - (403, 'Line exceeds 80 characters')
  - (403, 'Hardcoded string found')
  - (404, 'Line exceeds 80 characters')
  - (405, 'Line exceeds 80 characters')
  - (406, 'Line exceeds 80 characters')
  - (408, 'Line exceeds 80 characters')
  - (409, 'Line exceeds 80 characters')
  - (409, 'Hardcoded string found')
  - (410, 'Line exceeds 80 characters')
  - (410, 'Hardcoded string found')
  - (411, 'Line exceeds 80 characters')
  - (414, 'Line exceeds 80 characters')
  - (414, 'Hardcoded string found')
  - (415, 'Line exceeds 80 characters')
  - (415, 'Hardcoded string found')
  - (416, 'Line exceeds 80 characters')
  - (416, 'Hardcoded string found')
  - (417, 'Line exceeds 80 characters')
  - (417, 'Hardcoded string found')
  - (418, 'Line exceeds 80 characters')
  - (418, 'Hardcoded string found')
  - (419, 'Line exceeds 80 characters')
  - (420, 'Line exceeds 80 characters')
  - (421, 'Line exceeds 80 characters')
  - (421, 'Hardcoded string found')
  - (422, 'Line exceeds 80 characters')
  - (422, 'Hardcoded string found')
  - (423, 'Line exceeds 80 characters')
  - (423, 'Hardcoded string found')
  - (424, 'Line exceeds 80 characters')
  - (429, 'Line exceeds 80 characters')
  - (431, 'Line exceeds 80 characters')
  - (432, 'Line exceeds 80 characters')
  - (433, 'Line exceeds 80 characters')
  - (434, 'Line exceeds 80 characters')
  - (442, 'Line exceeds 80 characters')
  - (443, 'Line exceeds 80 characters')
  - (447, 'Missing docstring for function')
  - (453, 'Line exceeds 80 characters')
  - (454, 'Line exceeds 80 characters')
  - (459, 'Hardcoded string found')
  - (470, 'Line exceeds 80 characters')
  - (471, 'Line exceeds 80 characters')
  - (473, 'Line exceeds 80 characters')
  - (496, 'Line exceeds 80 characters')
  - (497, 'Line exceeds 80 characters')
  - (504, 'Line exceeds 80 characters')
  - (508, 'Line exceeds 80 characters')
  - (512, 'Line exceeds 80 characters')
  - (519, 'Line exceeds 80 characters')
  - (522, 'Line exceeds 80 characters')
  - (531, 'Line exceeds 80 characters')
  - (540, 'Line exceeds 80 characters')
  - (540, 'Hardcoded string found')
  - (547, 'Line exceeds 80 characters')
  - (548, 'Line exceeds 80 characters')
  - (549, 'Line exceeds 80 characters')
  - (554, 'Line exceeds 80 characters')
  - (558, 'Line exceeds 80 characters')
  - (559, 'Line exceeds 80 characters')
  - (563, 'Line exceeds 80 characters')
  - (567, 'Line exceeds 80 characters')
  - (572, 'Line exceeds 80 characters')
  - (576, 'Line exceeds 80 characters')
  - (578, 'Line exceeds 80 characters')
  - (580, 'Line exceeds 80 characters')
  - (583, 'Line exceeds 80 characters')
  - (584, 'Line exceeds 80 characters')
  - (586, 'Line exceeds 80 characters')
  - (587, 'Line exceeds 80 characters')
  - (592, 'Line exceeds 80 characters')
  - (605, 'Line exceeds 80 characters')
  - (607, 'Line exceeds 80 characters')
  - (610, 'Line exceeds 80 characters')
  - (612, 'Line exceeds 80 characters')
  - (615, 'Line exceeds 80 characters')
  - (617, 'Line exceeds 80 characters')
  - (618, 'Line exceeds 80 characters')
  - (619, 'Line exceeds 80 characters')
  - (620, 'Line exceeds 80 characters')
  - (625, 'Line exceeds 80 characters')
  - (630, 'Line exceeds 80 characters')
  - (644, 'Line exceeds 80 characters')
  - (644, 'Hardcoded string found')
  - (652, 'Hardcoded string found')
  - (653, 'Line exceeds 80 characters')
  - (653, 'Hardcoded string found')
Issues in commune/config/config_module.py:
  - (3, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (21, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
Issues in commune/model/remote/remote_model_client.py:
  - (11, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (41, 'Line exceeds 80 characters')
  - (46, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (55, 'Line exceeds 80 characters')
  - (55, 'Hardcoded string found')
  - (68, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
  - (85, 'Hardcoded string found')
  - (88, 'Line exceeds 80 characters')
  - (95, 'Hardcoded string found')
  - (98, 'Line exceeds 80 characters')
  - (98, 'Hardcoded string found')
  - (105, 'Hardcoded string found')
  - (106, 'Line exceeds 80 characters')
  - (106, 'Hardcoded string found')
  - (107, 'Hardcoded string found')
  - (108, 'Hardcoded string found')
  - (109, 'Line exceeds 80 characters')
  - (109, 'Hardcoded string found')
  - (110, 'Line exceeds 80 characters')
  - (110, 'Hardcoded string found')
  - (114, 'Hardcoded string found')
  - (115, 'Hardcoded string found')
  - (116, 'Hardcoded string found')
  - (125, 'Hardcoded string found')
Issues in commune/model/remote/remote_model_server.py:
  - (9, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (56, 'Line exceeds 80 characters')
  - (70, 'Line exceeds 80 characters')
  - (76, 'Line exceeds 80 characters')
  - (76, 'Hardcoded string found')
  - (103, 'Hardcoded string found')
  - (104, 'Hardcoded string found')
  - (108, 'Hardcoded string found')
  - (124, 'Hardcoded string found')
  - (146, 'Line exceeds 80 characters')
  - (150, 'Hardcoded string found')
  - (155, 'Hardcoded string found')
  - (156, 'Hardcoded string found')
  - (158, 'Hardcoded string found')
  - (160, 'Hardcoded string found')
  - (173, 'Hardcoded string found')
  - (174, 'Hardcoded string found')
Issues in commune/model/remote/utils.py:
  - (4, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
Issues in commune/model/transformer/huggingface_transformer.py:
  - (8, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (37, 'Line exceeds 80 characters')
  - (42, 'Line exceeds 80 characters')
  - (42, 'Hardcoded string found')
  - (77, 'Hardcoded string found')
  - (94, 'Hardcoded string found')
Issues in commune/ray/server/launcher/module.py:
  - (14, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (57, 'Line exceeds 80 characters')
  - (57, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (66, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
  - (71, 'Hardcoded string found')
  - (74, 'Line exceeds 80 characters')
  - (74, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (110, 'Hardcoded string found')
  - (112, 'Hardcoded string found')
  - (114, 'Hardcoded string found')
  - (115, 'Line exceeds 80 characters')
  - (116, 'Hardcoded string found')
  - (118, 'Hardcoded string found')
  - (132, 'Line exceeds 80 characters')
  - (138, 'Line exceeds 80 characters')
  - (138, 'Hardcoded string found')
  - (139, 'Hardcoded string found')
  - (141, 'Hardcoded string found')
  - (188, 'Line exceeds 80 characters')
  - (194, 'Hardcoded string found')
  - (199, 'Hardcoded string found')
  - (200, 'Hardcoded string found')
  - (201, 'Hardcoded string found')
  - (203, 'Hardcoded string found')
  - (204, 'Hardcoded string found')
Issues in commune/ray/server/launcher/module.yaml:
  - (5, 'Hardcoded string found')
Issues in commune/ray/server/launcher/utils.py:
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
Issues in commune/server/client_module.py:
  - (22, 'Hardcoded string found')
  - (34, 'Line exceeds 80 characters')
  - (39, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (62, 'Line exceeds 80 characters')
  - (87, 'Line exceeds 80 characters')
  - (89, 'Hardcoded string found')
  - (95, 'Hardcoded string found')
  - (107, 'Line exceeds 80 characters')
  - (133, 'Line exceeds 80 characters')
  - (136, 'Hardcoded string found')
  - (159, 'Hardcoded string found')
  - (160, 'Hardcoded string found')
Issues in commune/server/interceptor_module.py:
  - (19, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
  - (41, 'Line exceeds 80 characters')
  - (42, 'Hardcoded string found')
  - (74, 'Hardcoded string found')
  - (77, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (96, 'Line exceeds 80 characters')
  - (100, 'Hardcoded string found')
  - (109, 'Hardcoded string found')
  - (112, 'Hardcoded string found')
  - (116, 'Line exceeds 80 characters')
  - (116, 'Hardcoded string found')
  - (125, 'Hardcoded string found')
  - (128, 'Hardcoded string found')
  - (131, 'Line exceeds 80 characters')
  - (146, 'Line exceeds 80 characters')
  - (156, 'Line exceeds 80 characters')
Issues in commune/server/proto/server.proto:
  - (2, 'Line exceeds 80 characters')
Issues in commune/server/proto/server_pb2.py:
  - (23, 'Line exceeds 80 characters')
  - (30, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (43, 'Line exceeds 80 characters')
  - (45, 'Hardcoded string found')
  - (50, 'Line exceeds 80 characters')
  - (52, 'Hardcoded string found')
  - (57, 'Line exceeds 80 characters')
  - (74, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
  - (78, 'Line exceeds 80 characters')
  - (78, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
  - (89, 'Hardcoded string found')
  - (98, 'Hardcoded string found')
  - (110, 'Hardcoded string found')
Issues in commune/server/proto/server_pb2_grpc.py:
  - (39, 'Hardcoded string found')
  - (42, 'Line exceeds 80 characters')
  - (46, 'Hardcoded string found')
  - (66, 'Line exceeds 80 characters')
  - (70, 'Line exceeds 80 characters')
Issues in commune/server/serializer_module.py:
  - (2, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (25, 'Line exceeds 80 characters')
  - (33, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (39, 'Line exceeds 80 characters')
  - (41, 'Line exceeds 80 characters')
  - (44, 'Line exceeds 80 characters')
  - (54, 'Line exceeds 80 characters')
  - (68, 'Line exceeds 80 characters')
  - (68, 'Hardcoded string found')
  - (102, 'Line exceeds 80 characters')
  - (104, 'Hardcoded string found')
  - (105, 'Hardcoded string found')
  - (113, 'Hardcoded string found')
  - (116, 'Hardcoded string found')
  - (118, 'Line exceeds 80 characters')
  - (127, 'Line exceeds 80 characters')
  - (128, 'Line exceeds 80 characters')
  - (129, 'Line exceeds 80 characters')
  - (138, 'Line exceeds 80 characters')
  - (156, 'Line exceeds 80 characters')
  - (165, 'Hardcoded string found')
  - (171, 'Hardcoded string found')
  - (177, 'Line exceeds 80 characters')
  - (177, 'Hardcoded string found')
Issues in commune/server/server_module.py:
  - (3, 'Hardcoded string found')
  - (22, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
  - (31, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (70, 'Line exceeds 80 characters')
  - (71, 'Line exceeds 80 characters')
  - (72, 'Line exceeds 80 characters')
  - (76, 'Hardcoded string found')
  - (82, 'Line exceeds 80 characters')
Issues in docker-compose.yml:
  - (38, 'Line exceeds 80 characters')

**Comment by Ikekita** [comment]
I got it.
