### ISSUE TITLE
Issue-utils refactor

### ISSUE THREAD

**Issue by JamesRyo** [JamesRyo/Commune#12]
Automated Review Comments
Issues in commune/model/remote/remote_model_client.py:
  - (5, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
Issues in commune/model/remote/remote_model_server.py:
  - (7, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (71, 'Line exceeds 80 characters')
  - (81, 'Line exceeds 80 characters')
  - (86, 'Missing docstring for function')
  - (91, 'Line exceeds 80 characters')
  - (91, 'Missing docstring for function')
  - (97, 'Line exceeds 80 characters')
  - (103, 'Missing docstring for function')
  - (104, 'Hardcoded string found')
  - (105, 'Hardcoded string found')
  - (107, 'Hardcoded string found')
  - (131, 'Hardcoded string found')
  - (131, 'Missing docstring for function')
  - (142, 'Line exceeds 80 characters')
  - (143, 'Line exceeds 80 characters')
  - (149, 'Missing docstring for function')
Issues in commune/server/gateway/gateway_server.py:
  - (1, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
Issues in commune/server/server_module.py:
  - (13, 'Missing docstring for class')
  - (15, 'Hardcoded string found')
  - (33, 'Line exceeds 80 characters')
  - (34, 'Line exceeds 80 characters')
  - (35, 'Line exceeds 80 characters')
  - (37, 'Hardcoded string found')
  - (43, 'Line exceeds 80 characters')
  - (44, 'Hardcoded string found')
  - (47, 'Missing docstring for function')
  - (50, 'Hardcoded string found')
  - (72, 'Line exceeds 80 characters')
  - (75, 'Hardcoded string found')
Issues in commune/utils/__init__.py:
  - (50, 'Missing docstring for function')
  - (76, 'Line exceeds 80 characters')
  - (88, 'Hardcoded string found')
  - (90, 'Hardcoded string found')
  - (97, 'Line exceeds 80 characters')
  - (107, 'Hardcoded string found')
  - (144, 'Hardcoded string found')
  - (162, 'Hardcoded string found')
  - (233, 'Line exceeds 80 characters')
Issues in commune/utils/asyncio_utils.py:
  - (4, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
Issues in commune/utils/dict_utils.py:
  - (27, 'Line exceeds 80 characters')
  - (79, 'Hardcoded string found')
  - (94, 'Hardcoded string found')
  - (96, 'Hardcoded string found')
  - (116, 'Line exceeds 80 characters')
  - (137, 'Hardcoded string found')
  - (174, 'Hardcoded string found')
  - (192, 'Hardcoded string found')
  - (276, 'Line exceeds 80 characters')
  - (365, 'Line exceeds 80 characters')
  - (424, 'Line exceeds 80 characters')
  - (447, 'Line exceeds 80 characters')
  - (463, 'Line exceeds 80 characters')
  - (489, 'Line exceeds 80 characters')
  - (514, 'Hardcoded string found')
  - (515, 'Hardcoded string found')
  - (567, 'Line exceeds 80 characters')
  - (612, 'Hardcoded string found')
  - (622, 'Hardcoded string found')
  - (624, 'Hardcoded string found')
  - (626, 'Hardcoded string found')
  - (649, 'Hardcoded string found')
  - (659, 'Hardcoded string found')
  - (661, 'Hardcoded string found')
  - (663, 'Hardcoded string found')
Issues in commune/utils/function_utils.py:
  - (46, 'Line exceeds 80 characters')
  - (46, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
  - (68, 'Hardcoded string found')
  - (71, 'Hardcoded string found')
  - (73, 'Hardcoded string found')
  - (76, 'Hardcoded string found')
  - (77, 'Hardcoded string found')
  - (83, 'Line exceeds 80 characters')
  - (106, 'Hardcoded string found')
  - (116, 'Hardcoded string found')
  - (123, 'Hardcoded string found')
  - (128, 'Line exceeds 80 characters')
  - (137, 'Hardcoded string found')
  - (175, 'Hardcoded string found')
  - (189, 'Hardcoded string found')
  - (193, 'Hardcoded string found')
Issues in commune/utils/metric_utils.py:
  - (16, 'Hardcoded string found')
Issues in commune/utils/network_utils.py:
  - (16, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (36, 'Line exceeds 80 characters')
  - (48, 'Line exceeds 80 characters')
  - (66, 'Line exceeds 80 characters')
  - (98, 'Line exceeds 80 characters')
  - (116, 'Line exceeds 80 characters')
  - (124, 'Line exceeds 80 characters')
  - (138, 'Line exceeds 80 characters')
  - (150, 'Line exceeds 80 characters')
  - (166, 'Line exceeds 80 characters')
  - (170, 'Hardcoded string found')
  - (173, 'Hardcoded string found')
  - (175, 'Line exceeds 80 characters')
  - (177, 'Line exceeds 80 characters')
  - (178, 'Line exceeds 80 characters')
  - (178, 'Hardcoded string found')
Issues in commune/utils/os_utils.py:
  - (27, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
Issues in commune/utils/pandas_utils.py:
  - (15, 'Line exceeds 80 characters')
Issues in commune/utils/pickle_utils.py:
  - (6, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
Issues in commune/utils/time_utils.py:
  - (7, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Line exceeds 80 characters')
  - (23, 'Hardcoded string found')
  - (25, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
  - (38, 'Line exceeds 80 characters')
  - (38, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
Issues in commune/utils/torch_utils.py:
  - (42, 'Line exceeds 80 characters')
  - (42, 'Hardcoded string found')
Issues in nohup_reg_1.out:
  - (4, 'Line exceeds 80 characters')

**Comment by miyatsuko0602** [comment]
I got it.
