### ISSUE TITLE
Issue-subprocess fix

### ISSUE THREAD

**Issue by JamesRyo** [JamesRyo/Commune#14]
Automated Review Comments
Issues in commune/subprocess/module.py:
  - (5, 'Hardcoded string found')
  - (31, 'Missing docstring for function')
  - (43, 'Missing docstring for function')
  - (46, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (60, 'Missing docstring for function')
  - (69, 'Missing docstring for function')
  - (76, 'Line exceeds 80 characters')
  - (77, 'Line exceeds 80 characters')
  - (79, 'Hardcoded string found')
  - (102, 'Hardcoded string found')

**Comment by Ikekita** [comment]
I got it.
