### ISSUE TITLE
Issue-fixed issues with remotee model

### ISSUE THREAD

**Issue by JamesRyo** [JamesRyo/Commune#8]
Automated Review Comments
Issues in commune/bittensor/nucleus/remote_model.py:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (33, 'Line exceeds 80 characters')
  - (33, 'Hardcoded string found')
Issues in commune/server/server_module.py:
  - (11, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (29, 'Hardcoded string found')

**Comment by Ikekita** [comment]
I got it.
